### ISSUE TITLE
all files show as new (green)

### ISSUE THREAD

**Issue by depend** [igorzoriy/atom-git-status#7]
git status integration has been working greatly until 5 minutes ago. All files are showing new (green). The repo is clean. I tried to restart atom a couple of times but to no avail.

**Comment by igorzoriy** [comment]
Hi. Could you give me more info and screenshots for reproducing this bug?

**Comment by depend** [comment]
Hi, I rebooted my windows box now it's fine. I haven't rebooted the box for a few days. I think we can close it for now. Thanks.
