### ISSUE TITLE
Root directory is not getting highlighted.

### ISSUE THREAD

**Issue by royalpinto** [igorzoriy/atom-git-status#9]
Root directory is not getting highlighted for new/modified files when there is a new/modified file in the root directory or in the subdirectory.

<img width="240" alt="screen shot 2016-10-21 at 2 49 03 pm" src="https://cloud.githubusercontent.com/assets/1013699/19593406/0cb44252-979e-11e6-85a3-89ebb6964b23.png">

**Comment by igorzoriy** [comment]
@royalpinto https://github.com/atom/tree-view plugin is responsible for that panel.

**Comment by royalpinto** [comment]
You mean, `tree-view` plugin already has the functionality to highlight the `repository` ? or `atom-git-status` is not allowed to access/modify repository element and is controlled by `tree-view` ?

**Comment by igorzoriy** [comment]
I mean this plugin adds separate panel to show `git status` output and don't affect to other panels in atom.

**Comment by royalpinto** [comment]
Ah okay, got it. Thanks.

An additional plugin for tree-view called `tree-view-git-status` showed the expected output.
